---
- name: "dellemc.os9: get running config for interface"
  dellemc.os9.os9_command:
    commands: "show running-config interface {{ port_name }}"
  register: port_description_cmd
  connection: network_cli

- name: "dellemc.os9: get description from running config"
  ansible.builtin.set_fact:
    port_description: "{{ port_description_cmd.stdout[0] | regex_search('(?<=description ).+?(?=[\\n\\r])') }}"

- name: "dellemc.os9: Remove existing tagged vlans from port"
  dellemc.os9.os9_config:
    lines:
      - "no tagged {{ port_name }}"
    parents: ["interface range Vlan 2-4094"]
    match: none
  ignore_errors: true

- name: "dellemc.os9: Clean up console"
  dellemc.os9.os9_command:
    commands:
      - "end"
  ignore_errors: true

- name: "dellemc.os9: Remove existing untagged vlans from port"
  dellemc.os9.os9_config:
    lines:
      - "no untagged {{ port_name }}"
    parents: ["interface range Vlan 2-4094"]
    match: none
  ignore_errors: true

- name: "dellemc.os9: Clean up console"
  dellemc.os9.os9_command:
    commands:
      - "end"
  ignore_errors: true

- name: "dellemc.os9: reset interface to default (no switchport and shutdown)"
  dellemc.os9.os9_config:
    lines:
      - "default interface {{ port_name }}"
  connection: network_cli

- name: "dellemc.os9: reassign description"
  dellemc.os9.os9_config:
    lines:
      - "description {{ port_description }}"
    parents: ["interface {{ port_name }}"]
  connection: network_cli
  when: port_description != ""
