---
- name: "junos: create vlan"
  junos_command:
    commands:
      - config
      - "set vlans {{ _vlan_name }} vlan-id {{ _vlan_id }}"
      - commit
  register: result
  retries: 10
  delay: 5
  until: result.msg is not defined or result.msg.find(junos_retries_msg) == -1
  connection: network_cli
