---
- name: "junos: delete port"
  junos_command:
    commands:
      - config
      - "delete interfaces {{ port_name }}"
      - commit
  register: result
  retries: 10
  delay: 5
  until: result.msg is not defined or result.msg.find(junos_retries_msg) == -1
  connection: network_cli
