---
- name: "fos: set the switchport mode to access"
  fos_config:
    lines:
      - switchport mode access
    parents: interface {{ port_name }}
  connection: network_cli

- name: "fos: configure port settings"
  fos_config:
    lines:
      - switchport access vlan {{ _vlan_id }}
    parents: interface {{ port_name }}
  connection: network_cli

- name: "fos: administratively enable the port"
  fos_config:
    lines:
      - no shutdown
    parents: interface {{ port_name }}
  connection: network_cli
